apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-demo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-k8s-demo
  template:
    metadata:
      labels:
        app: python-k8s-demo
    spec:
      containers:
      - name: python-container
        image: ravipratapgiri/githubactions:latest
        ports:
        - containerPort: 5000
